Add interface details list to Realm Management RPC
astarte-platform/astarte_rpc pull request #88
Opened 2024-07-12 13:58 UTC by nedimtokic

Realm Management RPC: Allow to query all Realm interfaces with details

2024-07-12 14:05 UTC, Annopaolo requested changes
Good one! Some nitpicking:
- I'd call it `GetDetailedInterfacesList` (and related), to make it clear that the details are on each interface
- Please add a changelog line

2024-07-12 14:07 UTC, Annopaolo commented
Also, don't forget to update `lib/astarte_rpc/protocol/proto/realm_management/call.proto` and `lib/astarte_rpc/protocol/proto/realm_management/reply.proto`!

2024-07-12 14:29 UTC, nedimtokic commented on lib/astarte_rpc/protocol/proto/realm_management/get_interfaces_details_list_reply.proto
> +   repeated string interface = 1;
Changed.

2024-07-15 13:22 UTC, Annopaolo approved these changes

2024-07-15 13:22 UTC, merged